# This is a basic workflow that is manually triggered

run-name: "${{ github.event.inputs.tag }}"

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tag:
        description: 'You can rename this workflow.'
        default: 'Manual workflow'
        required: false
      keep-alive:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Do you want to keep the session alive? y/N'
        # Default value if no value is explicitly provided
        default: 'n'
        # Input has to be provided for the workflow to run
        required: true
      dist-path:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'The path within artifacts for archiving'
        # Default value if no value is explicitly provided
        default: '/home/runner/work/debugger-action/debugger-action/dist'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  debug:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: "Create a keep-alive file."
      if: ${{ github.event.inputs.keep-alive == 'y' }}
      run: touch /tmp/keepalive
    - name: "Make directory for dist"
      run: "mkdir -p ${{ github.event.inputs.dist-path }}"
    - uses: actions/checkout@v2
    - name: Setup Debug Session
      #uses: csexton/debugger-action@master
      run: bash -e ./tmate.sh
    - name: Waiting for connection closing
      run: bash -e ./waiting.sh
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
#        name: dist-without-markdown
        name: dist
        path: |
          ${{ github.event.inputs.dist-path }}
 #         !dist/**/*.md
      
